import turtle

union = turtle.Pen()
union.speed("slow")


def blue():
    union.color("blue")
    union.begin_fill()
    union.up()
    union.left(180)
    union.forward(150)
    union.left(180)
    union.down()
    union.forward(300)
    union.left(90)
    union.forward(200)
    union.left(90)
    union.forward(300)
    union.left(90)
    union.forward(200)
    union.left(90)
    union.end_fill()


def white():
    union.color("white")
    union.begin_fill()
    union.forward(120)
    union.left(90)
    union.forward(200)
    union.right(90)
    union.forward(60)
    union.right(90)
    union.forward(200)
    union.end_fill()

    union.left(90)
    union.forward(120)
    union.color("white")
    union.begin_fill()
    union.left(90)
    union.forward(70)
    union.left(90)
    union.forward(300)
    union.right(90)
    union.forward(60)
    union.right(90)
    union.forward(300)
    union.end_fill()

    union.left(90)
    union.forward(40)
    union.color("white")
    union.begin_fill()
    union.left(123)
    union.forward(309)

    union.right(34)
    union.forward(40)
    union.right(90)
    union.forward(36)
    union.right(57)
    union.forward(306)
    union.right(31)
    union.forward(40)
    union.right(91)
    union.forward(35)
    union.end_fill()

    union.color("white")
    union.begin_fill()
    union.up()
    union.forward(130)
    union.down()
    union.forward(35)
    union.right(90)
    union.forward(35)
    union.right(32)
    union.forward(312)
    union.right(58)
    union.forward(35)
    union.right(90)
    union.forward(35)
    union.right(33)
    union.forward(313)
    union.end_fill()


def red():
    union.color("red")
    union.begin_fill()
    union.up()
    union.right(57)
    union.forward(5)
    union.down()
    union.forward(25)
    union.right(90)
    union.forward(25)
    union.right(33)
    union.forward(328)
    union.right(57)
    union.forward(23)
    union.right(90)
    union.forward(23)
    union.right(33)
    union.forward(329)
    union.end_fill()

    union.begin_fill()
    union.up()
    union.left(123)
    union.forward(52)
    union.left(90)
    union.down()
    union.forward(300)
    union.right(90)
    union.forward(50)
    union.right(90)
    union.forward(300)
    union.right(90)
    union.forward(50)
    union.end_fill()

    union.up()
    union.forward(75)
    union.right(90)
    union.forward(125)
    union.down()
    union.begin_fill()
    union.right(90)
    union.forward(200)
    union.left(90)
    union.forward(45)
    union.left(90)
    union.forward(200)
    union.left(90)
    union.forward(45)
    union.end_fill()

    union.up()
    union.forward(128)
    union.left(90)
    union.forward(177)
    union.down()

    union.begin_fill()
    union.left(123)
    union.forward(319)
    union.right(33)
    union.forward(32)
    union.right(90)
    union.forward(30)
    union.right(57)
    union.forward(308)
    union.right(33)
    union.forward(35)
    union.right(90)
    union.forward(20)
    union.end_fill()

    union.up()
    union.forward(300)
    union.down()


blue()
white()
# red()
turtle.exitonclick()
